name: Build and Test Conda Package

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: build
          environment-file: sealir-tutorials/conda_environment.yml

      - name: Install conda-build
        run: |
          source $CONDA/bin/activate
          conda activate build
          conda install -y conda-build

      - name: Build and test package
        run: |
          source $CONDA/bin/activate
          conda activate build
          conda build conda-recipe
